name: CI CD Pipeline Task Hive
# Apenas o CI está configurado, o CD será configurado posteriormente
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  API_SECRET: ${{ secrets.API_SECRET }}
  DATABASE_URL: postgresql://task:hive@localhost:5432/taskhive

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build

    - name: Run unit tests
      run: pnpm run test:unit

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build
    - uses: ./.github/actions/docker-compose

    - name: Docker compose up
      run: pnpm docker:db

    - name: Migrate database
      run: pnpm migrate:postgres

    - name: Run e2e tests
      run: pnpm run test:e2e
